name: Asset Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          check-latest: true
      - name: Test optimiser
        run: mvn -B clean --file optimiser/pom.xml && mvn -B verify --file optimiser/pom.xml && mvn -B validate --file optimiser/pom.xml
      - name: Test server
        run: mvn -B clean --file optimiser/pom.xml && mvn -B verify --file optimiser/pom.xml && mvn -B validate --file server/pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          check-latest: true
      - name: Build optimiser with Maven
        run: mvn -B package --file optimiser/pom.xml
      - name: Install optimiser with Maven
        run: mvn -B install --file optimiser/pom.xml
      - name: Build server with Maven
        run: mvn -B package --file server/pom.xml
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            server/target/*.jar
